name: deploy

on:
  push:
    branches:
      - main

permissions:
  contents: read
  deployments: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create GitHub deployment
        uses: bobheadxi/deployments@v1
        id: deployment
        with:
          step: start
          token: ${{ secrets.GITHUB_TOKEN }}
          env: production

      - name: Deploy to Azure
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: ${{ secrets.AZURE_VM_USER }}
          key: ${{ secrets.AZURE_SSH_KEY }}
          script: |
            cd ~/pheidippides-api || exit 1
            
            echo "Pulling latest code from GitHub"
            git pull origin main || exit 1
            
            echo "Activating virtual environment"
            source ~/pheidippides-api/venv/bin/activate
            
            echo "Installing dependencies"
            pip install -r requirements.txt
            
            echo "Restarting FastAPI app"
            sudo systemctl restart fastapi
            
            echo "Deployment completed successfully"

      - name: Finish deployment
        uses: bobheadxi/deployments@v1
        if: always()
        with:
          step: finish
          token: ${{ secrets.GITHUB_TOKEN }}
          deployment_id: ${{ steps.deployment.outputs.deployment_id }}
          status: ${{ job.status }}
          env: ${{ steps.deployment.outputs.env }}
          env_url: http://102.37.155.61